#!/bin/bash
# Load config file
userdir=~/
gitdir=~/git
gitrepo=~/git/scripts
myself=~/git/scripts/afin
configfile=~/git/scripts/afin.conf
source ~/git/scripts/afin.conf
bashrcfile =~/.bashrc


# Parse arguments passed + help formatting
version() {
    echo "Version 0.1"
}
usage() {
        echo "Usage:   'afin [parameter] [argument]'"
        echo "example: 'afin    -i       desktop'"
        echo " "
        echo "                 '-i desktop' Install chain for desktops"
        echo "                 '-i server' Install chain for servers"
        echo " "
        echo "                 '-b' to set the .bashrc file"
        echo " "
        echo "                 '-c update' Updates (AFIN)* all new available code"
        echo "                     and instal sources from the repository"
        echo "                 '-c upload' Uploads all new available code"
        echo "                     to the repository"
        echo " "
        echo "                 '-e' Makes all files in the local code repository"
        echo "                      as executeable"
        echo "                 '-o' Opens the config file, for editting the"
        echo "                      install chain."
        echo "                 '-v' Displays version number"
}
# Start radiostation
packages_install() {
    if [ "$pckind" == "desktop" ]
        then
            sudo chmod +x $gitrepo
            eval afinupdate
        elif [ "$pckind" == "server" ]
        then
            sudo chmod +x $gitrepo
            eval afinupdate
        else
            wrong_arg
    fi
}
wrong_arg() {
    echo "Not a correct argument given. Sleeping three seconds."
    sleep 3s
    usage
}
code_repo() {
    if [ "$trans_type" == "update" ]
        then
            cd $gitrepo
            sudo git pull
            sleep 1s
            chmod_gitrepo
        elif [ "$trans_type" == "upload" ]
        then
            cd $gitrepo
            sudo git add .
            sudo git commit -m "automated upload"
            sudo git push origin master
        else
            wrong_arg
        fi
}
install_myself() {
    if [ ! -f $myself ]; then
        sudo apt-get install git
        eval mkdir $gitdir
        eval cd $gitdir
        eval git clone https://github.com/tomasvdmeer/scripts
        eval cd $gitrepo
        eval sudo chmod +x $gitrepo

        # something went wrong here eval echo "export PATH=$PATH:~/git/scripts" >> ~/.bashrc
        # make_arg
        echo "Now you're able to use the app afin in the terminal"
        echo "Setting up environment variables for the root of AFIN"
        sleep 5s
        make_arg
    else
        usage
fi
}
chmod_gitrepo() {
    eval sudo chmod -R +x $gitrepo
    echo "All scripts in '$gitrepo' are given executable rights."
}
openconfig() {
    eval leafpad $configfile
}
make_arg() {
    path1=(${!PATH@})
    var_fname=\$var_name
    bashrcfile=~/.bashrc
    if grep -o 'git/scripts' ~/.bashrc
    then
        echo "file is already up to date"
        sleep 5s
    else
        echo "export PATH=\$$path1:~/git/scripts" >> ~/.bashrc
        echo "Argument directory set... exiting in 10 seconds"
        echo ""
        echo "Argument directory set... exiting in 10 seconds"
        sleep 5s 
    fi
}
optspec="i:c:oevb*"
while getopts "$optspec" optchar
do
    case "${optchar}" in
        i) pckind=$OPTARG packages_install;;
        c) trans_type=$OPTARG code_repo ;;
        o) openconfig ;;
        e) chmod_gitrepo ;;
        v) version ;;
        b) make_arg ;;
        *) usage ;;
    esac
done
################################################Start of the script##############################################
if [ $# -eq 0 ];
then
    install_myself
    exit 0
fi