#!/bin/bash
source ~/git/scripts/afin.conf
            sudo apt-get update
            sudo apt-get install $packages_server -y
            sudo apt-get update
            echo ""
            echo ""
            echo ""
            echo ""
            echo ""
            echo ""
            echo ""
            echo ""
            echo "INSTALLATION DONE!"
            echo ""
            echo "Exit in 5 seconds..."
            echo ""
            sleep 10s
