#!/bin/bash
# Load config file
userdir=~/
gitdir=~/git
gitrepo=~/git/scripts
myself=~/git/scripts/afin
configfile=~/git/scripts/afin.conf
#source ~/git/scripts/afin.conf

# Parse arguments passed + help formatting
version() {
    echo "Version 0.1"
}
usage() {
        echo "Usage:   'afin [parameter] [argument]'"
        echo "example: 'afin    -i       desktop'"
        echo " "
        echo "                 '-i desktop' Install chain for desktops"
        echo "                 '-i server' Install chain for servers"
        echo " "
        echo "                 '-c update' Downloads all new available code"
        echo "                     from the repository"
        echo "                 '-c upload' Uploads all new available code"
        echo "                     to the repository"
        echo " "
        echo "                 '-e' Makes all files in the local code repository"
        echo "                      as executeable"
        echo "                 '-o' Opens the config file, for editting the"
        echo "                      install chain."
        echo "                 '-v' Displays version number"
}
# Start radiostation
packages_desktop() {
    eval sudo apt-get install $packages_desktop -y
    echo "installing packages for desktop"
}
packages_server() {
    eval sudo apt-get install $packages_server -y
}
update_code_local() {
    cd $gitrepo
    git pull
}
update_code_server() {
    cd $gitrepo
    sudo git add .
    sudo git commit -m "automated upload"
    sudo git push origin master
}
install_myself() {
    if [ ! -f $myself ]; then
        sudo apt-get install git
        eval mkdir $gitdir
        eval cd $gitdir
        eval git clone https://github.com/tomasvdmeer/scripts
        eval cd $gitrepo
        eval chmod +x $gitrepo
        # something went wrong here eval echo "export PATH=$PATH:~/git/scripts" >> ~/.bashrc
        make_arg
        echo "Now you're able to use the app afin in the terminal"
        sleep 30s
    else
        usage
fi
}
chmod_gitrepo() {
    eval chmod +x $gitrepo
    echo "All scripts in '$gitrepo' are given executable rights."
}
openconfig() {
    eval leafpad $configfile
}
make_arg() {
    var_name=(${!PATH@})
    var_fname=\$var_name
    bashrcfile=~/.bashrc
    if grep -o 'git/scripts' $bashrcfile 
    then
        echo "file is already up to date"
    else
    eval echo "export PATH=$var_fname:~/git/scripts" >> $bashrcfile
    fi
}
#########################################################################################################################
# Option parsing "controller"    ---- getopts  l:  the ":" means it is followed by a argument
optspec="abcdefgz*"
while getopts "$optspec" optchar
do
    case "${optchar}" in
        a) packages_desktop ;;
        b) packages_server ;;
        c) update_code_local ;;
        d) update_code_server ;;
        e) chmod_gitrepo ;;
        f) openconfig ;;
        z) version ;;
        *) usage ;;
    esac
done
if [ $# -eq 0 ];
then
    install_myself
    exit 0
fi