#!/bin/bash
# Load config file
userdir=~/
gitdir=~/git
gitrepo=~/git/scripts
myself=~/git/scripts/afterinstall
configfile=~/git/scripts/afterinstall.conf
#source ~/git/scripts/afterinstall.conf

# Parse arguments passed + help formatting
version() {
    echo "Version 0.1"
}
usage() {
        echo "Usage 'radio -a' installs all desktop packages from software-center"
        echo "            '-b' installs all server packages from software-center "
        echo "            '-c' Updates all scripts/codes locally at this computer"
        echo "                 from the code repository"
        echo "            '-d' Sends all newly created code to the repository"
        echo "            '-e' Marks all scripts/codes on this computer as"
        echo "                 executeable"
        echo "            '-f' Open the config file for package installation"
        echo "                 automation (installchain)"
        echo "            '-g' Future"
}
# Start radiostation
packages_desktop() {
    eval sudo apt-get install $packages_desktop -y
    echo "installing packages for desktop"
}
packages_server() {
    eval sudo apt-get install $packages_server -y
}
update_code_local() {
    cd $gitrepo
    git pull
}
update_code_server() {
    cd $gitrepo
    sudo git add .
    sudo git commit -m "automated upload"
    sudo git push origin master
}
install_myself() {
    if [ ! -f $myself ]; then
        sudo apt-get install git
        eval mkdir $gitdir
        eval cd $gitdir
        eval git clone https://github.com/tomasvdmeer/scripts
        eval cd $gitrepo
        eval chmod +x $gitrepo
        # something went wrong here eval echo "export PATH=$PATH:~/git/scripts" >> ~/.bashrc
    else
        usage
fi
}
chmod_gitrepo() {
    eval chmod +x $gitrepo
    echo "All scripts in '$gitrepo' are given executable rights."
}
openconfig() {
    eval leafpad $configfile
}
#########################################################################################################################
# Option parsing "controller"    ---- getopts  l:  the ":" means it is followed by a argument
optspec="abcdefz*"
while getopts "$optspec" optchar
do
    case "${optchar}" in
        a) packages_desktop ;;
        b) packages_server ;;
        c) update_code_local ;;
        d) update_code_server ;;
        e) chmod_gitrepo ;;
        f) openconfig ;;
        z) version ;;
        *) usage ;;
    esac
done
# Makes radio command default to help screen for usability
if [ $# -eq 0 ];
then
    install_myself
    exit 0
fi